name = "parsnip-chaos-falcon-aim"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"
DOMAIN_NAME = "parsnip-and-chaos-falcon.co"
APP_NAME = "Parsnip & Chaos Falcon AIM"
THEME_NAME = "parsnip-chaos-falcon"
ENABLE_SEASONAL_THEMES = true
ENABLE_SOUNDS = true

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[build]
command = "npm run build"

[assets]
directory = "dist"
binding = "ASSETS"

